version: '3.8'

services:
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=my-app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:



